backend:
  name: github
  repo: fanyegong/gatsbyOnNetlify

media_folder: static/assets # 媒体文件，一般是图片的存储路径
public_folder: assets # 媒体文件夹名称

display_url: https://your-website.cn # CMS 上展示一个指向你的网站的 URL

collections: # 收藏集，CMS 的侧边栏分类
  - name: blog
    label: Blog
    folder: src/markdown-pages
    create: true  # 允许新增
    fields: # 编辑文件时，需要填写的数据，会将其放在 frontmatter 中
      - { name: path, label: Path, required: false }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: tags, label: Tags,  widget: list}
      - { name: categories, label: Categories,  widget: list}
      - { name: body, label: Body, widget: markdown }
